spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URL}/realms/projectxeric
          jwk-set-uri: ${KEYCLOAK_URL}/realms/projectxeric/protocol/openid-connect/certs
springdoc:
  show-login-endpoint: true
  swagger-ui:
    oauth:
      use-pkce-with-authorization-code-grant: true
      client-id: projectxeric
    try-it-out-enabled: true
    use-root-path: true
server:
  port: 8082
  use-forward-headers: true
